#!/bin/bash

# Создаем файл executable.sh и записываем в него команду echo "Hello"
echo 'echo "Hello"' > executable.sh

# Устанавливаем права доступа 755 (rwxr-xr-x)
chmod 755 executable.sh

# Запускаем файл executable.sh
echo "Запуск executable.sh с правами 755:"
./executable.sh

# Изменяем права доступа на 644 (rw-r--r--)
chmod 644 executable.sh

# Пытаемся запустить файл executable.sh снова
echo "Попытка запустить executable.sh с правами 644:"
./executable.sh
